// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/subscription/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/subscription/domain/caching.go -destination=internal/mock/subscription/caching.go -package=mocksubscription
//

// Package mocksubscription is a generated GoMock package.
package mocksubscription

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/vocab-booster-server-app/core/appcontext"
	domain "github.com/namhq1989/vocab-booster-server-app/pkg/subscription/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// GetUserSubscriptionPlan mocks base method.
func (m *MockCachingRepository) GetUserSubscriptionPlan(ctx *appcontext.AppContext, userID string) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSubscriptionPlan", ctx, userID)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSubscriptionPlan indicates an expected call of GetUserSubscriptionPlan.
func (mr *MockCachingRepositoryMockRecorder) GetUserSubscriptionPlan(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSubscriptionPlan", reflect.TypeOf((*MockCachingRepository)(nil).GetUserSubscriptionPlan), ctx, userID)
}

// SetUserSubscriptionPlan mocks base method.
func (m *MockCachingRepository) SetUserSubscriptionPlan(ctx *appcontext.AppContext, userID, plan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserSubscriptionPlan", ctx, userID, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserSubscriptionPlan indicates an expected call of SetUserSubscriptionPlan.
func (mr *MockCachingRepositoryMockRecorder) SetUserSubscriptionPlan(ctx, userID, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserSubscriptionPlan", reflect.TypeOf((*MockCachingRepository)(nil).SetUserSubscriptionPlan), ctx, userID, plan)
}
