// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/exercise/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=pkg/exercise/domain/queue.go -destination=internal/mock/exercise/queue.go -package=mockexercise
//

// Package mockexercise is a generated GoMock package.
package mockexercise

import (
	reflect "reflect"

	domain "github.com/namhq1989/vocab-booster-server-app/pkg/exercise/domain"
	appcontext "github.com/namhq1989/vocab-booster-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// ExerciseAnswered mocks base method.
func (m *MockQueueRepository) ExerciseAnswered(ctx *appcontext.AppContext, payload domain.QueueExerciseAnsweredPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExerciseAnswered", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExerciseAnswered indicates an expected call of ExerciseAnswered.
func (mr *MockQueueRepositoryMockRecorder) ExerciseAnswered(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExerciseAnswered", reflect.TypeOf((*MockQueueRepository)(nil).ExerciseAnswered), ctx, payload)
}

// GamificationExerciseAnswered mocks base method.
func (m *MockQueueRepository) GamificationExerciseAnswered(ctx *appcontext.AppContext, payload domain.QueueExerciseAnsweredPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GamificationExerciseAnswered", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// GamificationExerciseAnswered indicates an expected call of GamificationExerciseAnswered.
func (mr *MockQueueRepositoryMockRecorder) GamificationExerciseAnswered(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GamificationExerciseAnswered", reflect.TypeOf((*MockQueueRepository)(nil).GamificationExerciseAnswered), ctx, payload)
}
